name = "NelsonRules"
uuid = "f967765a-671f-4dab-8ad7-3d510d8fd276"
authors = ["Philip Tellis <philip.tellis@gmail.com>"]
version = "1.0.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
